version: "2.23.1"

networks:
  typeorm-rest-api:

services:
  mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - typeorm-rest-api
    ports:
      - "3308:3306"

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    command: npm run dev
    ports:
      - "3001:3001"
    networks:
      - typeorm-rest-api

volumes:
  mysql:
